version: '3.9'
services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    hostname: doner_kebab_house_api_db
    container_name: doner_kebab_house_api_db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db_data:/var/lib/mysql
